### ISSUE TITLE
NPM require doesn't work

### ISSUE THREAD

**Issue by VCNinc** [survirtual/ring-crypto#4]
No "main" on package.json - can't use with node/require

**Comment by survirtual** [comment]
Woops.  Yeah, I made this originally for use in a browser environment, clearly seems I did not test the package with node.

Have not been maintaining this package so it is mainly for reference at this point.

**Comment by survirtual** [comment]
I updated the package.json to include a "main" and pushed a new version to NPM.  This should be resolved now.
