### ISSUE TITLE
Ring-crypto dosen't work

### ISSUE THREAD

**Issue by XinwenXiang** [survirtual/ring-crypto#6]
I don't know whether the repository code is still being maintained, when i run `npm install ring-crypto` and try to use it for test, it dosen't work.
![image](https://user-images.githubusercontent.com/33709586/194733981-ae535c40-a5f9-469a-95c6-99afbbdc3583.png)
and the error info as follows:
![image](https://user-images.githubusercontent.com/33709586/194733996-fab3bb6a-d8c2-41d5-9d48-c2385fb0a692.png)

**Comment by survirtual** [comment]
This code is unmaintained.  I believe the package.json is not configured correctly and it uses only ES6 modules.  I don't know though, would have to look into it when I have more time.

I might release a new version in the future.  I didn't realize anyone was using it / interested.  I rewrote everything in Rust and it has a much better pipeline into wasm than all the plumbing I wrote myself for this one.

**Comment by XinwenXiang** [comment]
> 

Thanks for your reply.
I think it may caused by your function export and tsconfig.json, cuz I run this repo by just use 'npm install riing-crypto' and git this repo. Nomatter  write my own package.json and change the the env-config, or just adjust it with your repo, it can't work.
I'm interested in this project because I'm about to do some cryptographic implementation and wasm work, hope you can take a look if it is convenient for you.
Best regards.

**Comment by survirtual** [comment]
I updated the package.json to include a "main" and pushed a new version to NPM.  This should be resolved now.

Note: you may have to do something like 'import * as ring from "ring-crypto"; const crypt = ring.Crypto;' to access it.  I only tested the changes for the package itself using a require in nodejs and not module imports or TS.
